#!/bin/bash -e

info() {
    echo -e "\e[1m\e[96m[factory-reset]:\e[0m\e[1m $1\e[0m"
}

remove_files () {
WHITELIST="^/tree
^/dev
^/efi
^/etc
^/run
^/usr
^/var/lib/apt/gen
^/var/lib/apt/extended_states
^/var/lib/dkms
^/var/lib/dpkg
^/var/log/journal$
^/usr/lib/locale/locale-archive
^/root
^/home
^/proc
^/sys
/\.updated$"
    DPKG_FILES="$(mktemp)"
    ALL_FILES="$(mktemp)"
    RM_FILES="$(mktemp)"
    PATTERN_FILES="$(mktemp)"
    info '[1/4] Un-mounting bind-mounts ...'
    umount /debs || true
    umount /var/cache/acbs/tarballs || true
    info '[2/4] Listing dpkg packages ...'
    PACKAGES="$(dpkg-query --show --showformat="\${Package}\n")"
    info '[3/4] Collecting files from dpkg ...'
    find / -mindepth 2 >> "$ALL_FILES"
    for p in $PACKAGES; do
        dpkg-query --listfiles "$p" >> "$DPKG_FILES"
    done
    echo "$WHITELIST" > "$PATTERN_FILES"
    grep -vEf "$PATTERN_FILES" < "$ALL_FILES" > "${ALL_FILES}.new"
    mv "${ALL_FILES}.new" "$ALL_FILES"
    grep -vxFf "$DPKG_FILES" < "$ALL_FILES" > "$RM_FILES"
    info '[4/4] Removing files ...'
    xargs -L 1000 -a "$RM_FILES" rm -rfv
    rm -fv "$ALL_FILES" "$DPKG_FILES" "$RM_FILES"
}

CIEL_INST="${1:-$CIEL_INST}"
[ -z "$CIEL_INST" ] && ( echo "No instance specified" && exit 1 )
ciel down -i "$CIEL_INST"
ciel mount -i "$CIEL_INST"
declare -f remove_files > "$CIEL_INST/rm-script"
echo "remove_files; rm -fv '/rm-script'" >> "$CIEL_INST/rm-script"
chmod a+x "$CIEL_INST/rm-script"
ciel shell -i "$CIEL_INST" "/rm-script"
