#!/bin/bash
# Usage: ciel-generate <recipe>, one recipe at a time.

cat << EOF
You, here! Are you still using \`ciel generate\`? That is not advanced!
Please use \`aoscbootstrap\` instead. More information available at https://github.com/AOSC-Dev/aoscbootstrap.
EOF
exit 1
