complete -c ciel -n "__fish_use_subcommand" -s C -d 'set the CIEL! working directory'
complete -c ciel -n "__fish_use_subcommand" -s b -l batch -d 'batch mode, no input required'
complete -c ciel -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_use_subcommand" -f -a "version" -d 'display the version of CIEL!'
complete -c ciel -n "__fish_use_subcommand" -f -a "init" -d 'initialize the work directory'
complete -c ciel -n "__fish_use_subcommand" -f -a "load-os" -d 'unpack OS tarball or fetch the latest BuildKit from the repository'
complete -c ciel -n "__fish_use_subcommand" -f -a "load-tree" -d 'clone package tree from the link provided or AOSC OS ABBS main repository'
complete -c ciel -n "__fish_use_subcommand" -f -a "new" -d 'Create a new CIEL workspace'
complete -c ciel -n "__fish_use_subcommand" -f -a "list" -d 'list all the instances under the specified working directory'
complete -c ciel -n "__fish_use_subcommand" -f -a "add" -d 'add a new instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "del" -d 'remove an instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "shell" -d 'start an interactive shell'
complete -c ciel -n "__fish_use_subcommand" -f -a "run" -d 'lower-level version of \'shell\', without login environment, without sourcing ~/.bash_profile'
complete -c ciel -n "__fish_use_subcommand" -f -a "config" -d 'configure system and toolchain for building interactively'
complete -c ciel -n "__fish_use_subcommand" -f -a "commit" -d 'commit changes onto the shared underlying OS'
complete -c ciel -n "__fish_use_subcommand" -f -a "doctor" -d 'diagnose problems (hopefully)'
complete -c ciel -n "__fish_use_subcommand" -f -a "build" -d 'build the packages using the specified instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "rollback" -d 'rollback all or specified instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "down" -d 'shutdown and unmount all or one instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "stop" -d 'shuts down an instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "mount" -d 'mount all or specified instance'
complete -c ciel -n "__fish_use_subcommand" -f -a "farewell" -d 'remove everything related to CIEL!'
complete -c ciel -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c ciel -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from load-os" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from load-os" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from load-tree" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from load-tree" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from del" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from del" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from shell" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from shell" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from run" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from run" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from config" -s g
complete -c ciel -n "__fish_seen_subcommand_from config" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from config" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from commit" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from commit" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from doctor" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from doctor" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from build" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from build" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from rollback" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from rollback" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from down" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from down" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from stop" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from stop" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from mount" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from mount" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from farewell" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from farewell" -s V -l version -d 'Prints version information'
complete -c ciel -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c ciel -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
