name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config libsystemd-dev liblzma-dev libdbus-1-dev

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
